export const colorPickerTranslations = {
  'colorPicker.description':
    'A form control for choosing a color. The trigger shows the current swatch; the popover holds a native color input, format switch, value field, alpha, and optional presets.',
  'colorPicker.examples.basic.description':
    'Use sanring-color-picker when a form needs a color without building a custom picker.',
  'colorPicker.usage.description':
    'Import ColorPickerComponent and bind valueChange or Angular forms. Incoming hex, rgb, and hsl are parsed; the emitted string follows format.',
  'colorPicker.installation.description':
    'Install color-picker. It also pulls in popover, input, and field. Label the trigger with ariaLabel or ariaLabelledBy.',
  'colorPicker.demo.swatches': 'Presets',
  'colorPicker.demo.formats': 'Formats',
  'colorPicker.demo.disabled': 'Disabled',
  'colorPicker.demo.field': 'With Field',
  'colorPicker.demo.brand': 'Brand color',
  'colorPicker.demo.locked': 'Locked color',
  'colorPicker.examples.swatches.description':
    'Pass swatches as hex, rgb, or hsl. The selected chip matches the current color, not the string spelling.',
  'colorPicker.examples.formats.description':
    'Set format to emit rgb() or hsl(). The popover can also switch formats; alpha becomes 8-digit hex, rgba(), or hsl() with slash alpha.',
  'colorPicker.examples.field.description':
    'Wrap sanring-color-picker in sanring-field and bind a reactive form control.',
  'colorPicker.api.description': 'Inputs and outputs supported by sanring-color-picker.',
  'colorPicker.api.class.description': 'Additional classes merged with the host.',
  'colorPicker.api.id.description': 'The trigger id. Generated by default.',
  'colorPicker.api.value.description':
    'Current color. Accepts #rgb, #rrggbb, #rrggbbaa, rgb()/rgba(), and hsl()/hsla(). Emitted in the selected format.',
  'colorPicker.api.format.description':
    "Output syntax: 'hex', 'rgb', or 'hsl'. Defaults to hex. Switching formats emits the same color in the new syntax.",
  'colorPicker.api.disabled.description': 'Disables the trigger and the popover controls.',
  'colorPicker.api.invalid.description': 'Marks the trigger as invalid independently of Angular forms.',
  'colorPicker.api.required.description': 'Marks the control as required for sanring-field.',
  'colorPicker.api.swatches.description': 'Optional preset colors shown as chips in the popover.',
  'colorPicker.api.valueChange.description': 'Emits the next formatted color string after user interaction.',
  'colorPicker.api.ariaLabel.description': 'Accessible name for the trigger when no visible label is associated.',
  'colorPicker.api.ariaLabelledBy.description': 'Id of the visible label that names the trigger.',
  'colorPicker.api.ariaDescribedBy.description': 'Id of helper text that describes the control.',
  'colorPicker.api.colorInputLabel.description': 'Accessible name for the native color input inside the popover.',
  'colorPicker.api.valueInputLabel.description': 'Accessible name for the formatted value field inside the popover.',
  'colorPicker.api.hexInputLabel.description': 'Optional override for the value field accessible name.',
  'colorPicker.api.alphaInputLabel.description': 'Visible and accessible name for the alpha slider.',
  'colorPicker.api.formatGroupLabel.description': 'Accessible name for the hex / rgb / hsl switch.',
  'colorPicker.accessibility.description':
    "The trigger is a button with aria-haspopup='dialog'. The panel is role='dialog'. Format buttons use aria-pressed. Native color, value, and alpha have their own labels. Preset chips use aria-pressed. Works with sanring-field for automatic aria-describedby wiring.",
  'colorPicker.keyboard.description':
    'Open the popover from the trigger, then tab through format, native color, alpha, value, and presets.',
  'colorPicker.keyboard.enterSpace': 'Opens or closes the popover from the trigger.',
  'colorPicker.keyboard.escape': 'Closes the popover.',
  'colorPicker.keyboard.tab': 'Moves focus through the trigger, then the popover controls.',
  'colorPicker.stateModel.description':
    'Implements ControlValueAccessor. Use [(ngModel)] or formControl. Value type: string. Internal model is RGBA; format chooses hex, rgb(), or hsl(). Alpha below 1 emits 8-digit hex, rgba(), or hsl() with slash alpha. Named colors, oklch, and color-mix() are rejected.',
} as const;
