export const colorPickerTranslations = {
  'colorPicker.description':
    'A form control for choosing a hex color. The trigger shows the current swatch; the popover holds a native color input, hex field, and optional presets.',
  'colorPicker.examples.basic.description':
    'Use sanring-color-picker when a form needs a hex color without building a custom picker.',
  'colorPicker.usage.description':
    'Import ColorPickerComponent and bind valueChange or Angular forms. The value is always a lowercase #rrggbb string.',
  'colorPicker.installation.description':
    'Install color-picker. It also pulls in popover, input, and field. Label the trigger with ariaLabel or ariaLabelledBy.',
  'colorPicker.demo.swatches': 'Presets',
  'colorPicker.demo.disabled': 'Disabled',
  'colorPicker.demo.field': 'With Field',
  'colorPicker.demo.brand': 'Brand color',
  'colorPicker.demo.locked': 'Locked color',
  'colorPicker.examples.swatches.description':
    'Pass swatches to show preset chips. 3-digit hex values expand to #rrggbb.',
  'colorPicker.examples.field.description':
    'Wrap sanring-color-picker in sanring-field and bind a reactive form control.',
  'colorPicker.api.description': 'Inputs and outputs supported by sanring-color-picker.',
  'colorPicker.api.class.description': 'Additional classes merged with the host.',
  'colorPicker.api.id.description': 'The trigger id. Generated by default.',
  'colorPicker.api.value.description':
    'Current color as #rgb or #rrggbb. Stored and emitted as lowercase #rrggbb.',
  'colorPicker.api.disabled.description': 'Disables the trigger and the popover controls.',
  'colorPicker.api.invalid.description': 'Marks the trigger as invalid independently of Angular forms.',
  'colorPicker.api.required.description': 'Marks the control as required for sanring-field.',
  'colorPicker.api.swatches.description': 'Optional preset hex colors shown as chips in the popover.',
  'colorPicker.api.valueChange.description': 'Emits the next #rrggbb value after user interaction.',
  'colorPicker.api.ariaLabel.description': 'Accessible name for the trigger when no visible label is associated.',
  'colorPicker.api.ariaLabelledBy.description': 'Id of the visible label that names the trigger.',
  'colorPicker.api.ariaDescribedBy.description': 'Id of helper text that describes the control.',
  'colorPicker.api.colorInputLabel.description': 'Accessible name for the native color input inside the popover.',
  'colorPicker.api.hexInputLabel.description': 'Accessible name for the hex text field inside the popover.',
  'colorPicker.accessibility.description':
    "The trigger is a button with aria-haspopup='dialog'. The panel is role='dialog'. Native color and hex fields have their own labels. Preset chips use aria-pressed. Works with sanring-field for automatic aria-describedby wiring.",
  'colorPicker.keyboard.description':
    'Open the popover from the trigger, then tab through the native color input, hex field, and presets.',
  'colorPicker.keyboard.enterSpace': 'Opens or closes the popover from the trigger.',
  'colorPicker.keyboard.escape': 'Closes the popover.',
  'colorPicker.keyboard.tab': 'Moves focus through the trigger, then the popover controls.',
  'colorPicker.stateModel.description':
    'Implements ControlValueAccessor. Use [(ngModel)] or formControl. Value type: string. Invalid hex is kept as a draft and reverted on blur; 3-digit hex expands to #rrggbb.',
} as const;
