export const otpInputTranslations = {
  'otpInput.description':
    'A one-time password input for verification codes with paste, keyboard navigation, and Angular forms support.',
  'otpInput.examples.basic.description':
    'Use sanring-otp-input when users need to enter short verification codes one character at a time.',
  'otpInput.usage.description':
    'Import OtpInputComponent and bind valueChange or Angular forms to receive the code string.',
  'otpInput.installation.description':
    'Install the OTP input component and provide an accessible label with ariaLabel or ariaLabelledBy.',
  'otpInput.demo.pattern': 'Pattern',
  'otpInput.demo.separator': 'Separator',
  'otpInput.demo.alphanumeric': 'Alphanumeric',
  'otpInput.demo.disabled': 'Disabled',
  'otpInput.demo.controlled': 'Controlled',
  'otpInput.demo.invalid': 'Invalid',
  'otpInput.demo.fourDigits': 'Four Digits',
  'otpInput.demo.form': 'Form',
  'otpInput.demo.field': 'With Field',
  'otpInput.demo.verificationCode': 'Verification code',
  'otpInput.demo.digitsOnly': 'Digits only',
  'otpInput.demo.recoveryCode': 'Recovery code',
  'otpInput.demo.pinCode': 'PIN code',
  'otpInput.demo.controlledDescription': 'Enter your one-time password.',
  'otpInput.demo.invalidError': 'Invalid verification code.',
  'otpInput.demo.fieldError': 'Enter the 6-digit code.',
  'otpInput.demo.verifyLogin': 'Verify your login',
  'otpInput.demo.formDescription': 'Enter the verification code we sent to your email address.',
  'otpInput.demo.verify': 'Verify',
  'otpInput.examples.invalid.description':
    'Bind a form control and mark it touched to render the invalid state on every slot.',
  'otpInput.examples.field.description':
    'Wrap sanring-otp-input in sanring-field to share labels, descriptions, and validation messages with the rest of the form system.',
  'otpInput.examples.form.description':
    'Use sanring-otp-input with sanring-field and a submit button for complete verification forms.',
  'otpInput.api.description': 'Inputs and outputs supported by sanring-otp-input.',
  'otpInput.api.class.description': 'Additional classes merged with the OTP input root.',
  'otpInput.api.id.description': 'The group id. Generated by default.',
  'otpInput.api.name.description': 'Name forwarded to the hidden native input for form context.',
  'otpInput.api.length.description': 'Number of slots rendered for the code.',
  'otpInput.api.value.description': 'Current code value. Invalid characters are ignored.',
  'otpInput.api.type.description': 'Character filter used by typing and paste handling.',
  'otpInput.api.pattern.description':
    'Custom character pattern. When provided, it takes precedence over type.',
  'otpInput.api.size.description': 'Visual size applied to each slot.',
  'otpInput.api.orientation.description':
    'Controls whether slots are laid out horizontally or vertically.',
  'otpInput.api.textAlign.description': 'Text alignment inside each slot.',
  'otpInput.api.separatorAt.description':
    'Optional slot boundary, or boundaries, where the default renderer inserts sanring-otp-input-separator.',
  'otpInput.api.autocomplete.description':
    'Autocomplete hint forwarded to the hidden native input. Defaults to one-time-code.',
  'otpInput.api.disabled.description': 'Disables all slots and prevents user interaction.',
  'otpInput.api.readOnly.description': 'Keeps the value visible while preventing edits.',
  'otpInput.api.required.description':
    'Marks the OTP input as required for field integration and aria-required.',
  'otpInput.api.ariaLabel.description':
    'Accessible label for the group and hidden input when no visible label is associated.',
  'otpInput.api.ariaLabelledBy.description':
    'ID of the visible label element that names the OTP input.',
  'otpInput.api.ariaDescribedBy.description':
    'ID of helper text that describes the OTP input; merged with Field-provided description ids.',
  'otpInput.api.valueChange.description': 'Emits the next code string after user interaction.',
  'otpInput.api.stateChange.description':
    'Emits the next code string together with slot metadata and completion state.',
  'otpInput.api.complete.description': 'Emits when every slot has a value.',
  'otpInput.api.pasted.description':
    'Emits normalized paste details after a paste event is handled.',
  'otpInput.api.slotKeydown.description':
    'Emits per-slot keyboard metadata for advanced custom slot handling.',
  'otpInput.accessibility.description':
    "role='group' on the host, aria-label / aria-labelledby, aria-describedby, aria-invalid, aria-required, and aria-disabled are synced automatically. The visual slots are hidden from assistive technology, while one transparent native input receives the complete code and supports password managers and one-time-code autofill.",
  'otpInput.keyboard.description': 'The native input provides navigation across the visual slots.',
  'otpInput.keyboard.type': 'Type a character to fill the focused slot and advance to the next.',
  'otpInput.keyboard.arrowLeftRight': 'Move focus to the adjacent slot.',
  'otpInput.keyboard.backspace': 'Clear the current slot and move focus to the previous slot.',
  'otpInput.keyboard.delete': 'Clear the current slot without moving focus.',
  'otpInput.stateModel.description':
    'Implements ControlValueAccessor. Use [(ngModel)] or formControl. Value type: string. The complete output fires when every slot has a character, making it easy to auto-submit verification forms.',
} as const;
