export const radioTranslations = {
  'radio.description':
    'A set of radio buttons backed by ControlValueAccessor, with full keyboard navigation (roving tabindex) and WAI-ARIA compliance.',
  'radio.examples.basic.description':
    'A RadioGroup backed by ControlValueAccessor — use ngModel or reactive forms to bind the selected value.',
  'radio.usage.description':
    'Import RadioGroupComponent and RadioItemComponent, wrap items inside the group, and bind the value.',
  'radio.examples.description':
    'Common patterns including labeled items, horizontal layout, and disabled states.',
  'radio.demo.withLabel': 'With Labels',
  'radio.demo.horizontal': 'Horizontal',
  'radio.demo.disabled': 'Disabled',
  'radio.demo.field': 'With Field',
  'radio.demo.planFree': 'Free',
  'radio.demo.planPro': 'Pro',
  'radio.demo.fieldError': 'Please choose a plan.',
  'radio.examples.field.description':
    'Wrap sanring-radio-group in sanring-field and bind a reactive form control — the error message shows automatically once the control is invalid and touched.',
  'radio.api.group.title': 'RadioGroupComponent',
  'radio.api.group.description': 'Inputs and outputs for the radio group container.',
  'radio.api.item.title': 'RadioItemComponent',
  'radio.api.item.description': 'Inputs for each individual radio button.',
  'radio.api.group.id': 'ID applied to the radiogroup element. Generated by default.',
  'radio.api.group.class': 'Additional classes merged with the group container.',
  'radio.api.group.name':
    'Name hint for the group; forwarded to individual items for form context.',
  'radio.api.group.disabled': 'Disables all items in the group.',
  'radio.api.group.required': 'Sets aria-required on the group to signal a mandatory field.',
  'radio.api.group.orientation':
    'Layout direction. Accepts RadioOrientation.Vertical (default) or RadioOrientation.Horizontal.',
  'radio.api.group.value':
    'Controlled selected value. Use with [(value)] for two-way binding without Angular forms.',
  'radio.api.group.valueChange': 'Emits the new RadioValue whenever the selection changes.',
  'radio.api.group.ariaLabel': 'Accessible label for the group when no visible heading is present.',
  'radio.api.group.ariaLabelledBy': 'ID of an external element that labels the group.',
  'radio.api.group.ariaDescribedBy':
    'ID of an element that provides an extended description for the group.',
  'radio.api.item.class': 'Additional classes merged with the radio button.',
  'radio.api.item.id': 'Native id applied to the button; use with <label for="…"> for association.',
  'radio.api.item.value': 'The RadioValue this item represents. Required.',
  'radio.api.item.disabled': 'Disables this individual item regardless of the group state.',
  'radio.api.item.ariaLabel':
    'Accessible label for standalone items without a visible label element.',
  'radio.api.item.ariaLabelledBy': 'ID of an external element that labels this item.',
  'radio.api.item.ariaDescribedBy':
    'ID of an element that provides an extended description for this item.',
  'radio.accessibility.description': "role='radiogroup' on sanring-radio-group, role='radio' on each sanring-radio. aria-checked, aria-disabled, and aria-required are synced automatically. When nested in sanring-field, aria-labelledby and aria-describedby are wired to the group.",
  'radio.keyboard.description': 'Roving tabindex keeps only one item in the tab sequence at a time.',
  'radio.keyboard.tab': 'Move focus into the group. Focus lands on the checked item, or the first enabled item if none is checked.',
  'radio.keyboard.arrowUpDown': 'Navigate between radio items and immediately select the focused item.',
  'radio.keyboard.space': 'Select the currently focused radio item.',
  'radio.stateModel.description': 'sanring-radio-group implements ControlValueAccessor. Use [(ngModel)] or formControl on the group element. Value type: string | null. The valueChange output and [(value)] are available for forms-free binding.',
} as const;
