export const sidebarTranslations = {
  'sidebar.description':
    'A composable app-shell navigation area with optional offcanvas and icon-rail collapse modes.',
  'sidebar.examples.basic.description':
    'A sidebar participates in page layout and can collapse without becoming a modal overlay.',
  'sidebar.usage.description':
    'Use sidebar primitives to compose application navigation, account switchers, grouped links, and footer actions.',
  'sidebar.installation.description':
    'Install the sidebar primitives and import the convenience array or individual building blocks.',
  'sidebar.composition.description':
    'The sidebar keeps structure separate from interactive links. Use menu button as a directive on anchors or buttons.',
  'sidebar.demo.platform': 'Platform',
  'sidebar.demo.dashboard': 'Dashboard',
  'sidebar.demo.customers': 'Customers',
  'sidebar.demo.notifications': 'Notifications',
  'sidebar.demo.settings': 'Settings',
  'sidebar.demo.overview': 'Overview',
  'sidebar.demo.reports': 'Reports',
  'sidebar.demo.accounts': 'Accounts',
  'sidebar.demo.segments': 'Segments',
  'sidebar.demo.inbox': 'Inbox',
  'sidebar.demo.rules': 'Rules',
  'sidebar.demo.teams': 'Teams',
  'sidebar.demo.switchTeam': 'Switch team',
  'sidebar.demo.addTeam': 'Add team',
  'sidebar.demo.projects': 'Projects',
  'sidebar.demo.designEngineering': 'Design Engineering',
  'sidebar.demo.salesMarketing': 'Sales & Marketing',
  'sidebar.demo.travel': 'Travel',
  'sidebar.demo.more': 'More',
  'sidebar.demo.projectActions': 'Project actions',
  'sidebar.demo.viewProject': 'View Project',
  'sidebar.demo.shareProject': 'Share Project',
  'sidebar.demo.deleteProject': 'Delete Project',
  'sidebar.demo.accountMenu': 'Account menu',
  'sidebar.demo.upgradeToPro': 'Upgrade to Pro',
  'sidebar.demo.account': 'Account',
  'sidebar.demo.billing': 'Billing',
  'sidebar.demo.logOut': 'Log out',
  'sidebar.demo.toggle': 'Toggle sidebar',
  'sidebar.demo.iconMode': 'Icon rail',
  'sidebar.demo.offcanvasMode': 'Offcanvas',
  'sidebar.demo.noneMode': 'No collapse',
  'sidebar.api.description':
    'Sidebar inputs control identity, collapse strategy, state, and link presentation.',
  'sidebar.api.id.description':
    'Sets the id used by trigger aria-controls. A stable id is generated by default.',
  'sidebar.api.open.description':
    'Controls the expanded state. Supports two-way binding with [(open)]. Ignored when collapsible is none.',
  'sidebar.api.collapsible.description':
    'Defines the closed behavior: none stays open, offcanvas collapses to zero width, and icon keeps a compact rail.',
  'sidebar.api.class.description': 'Merges extra classes into the sidebar or slot host element.',
  'sidebar.api.role.description':
    'Landmark role for the sidebar root. Use navigation when the whole region is navigation.',
  'sidebar.api.ariaLabel.description':
    'Accessible name for the sidebar landmark when ariaLabelledBy is not set.',
  'sidebar.api.ariaLabelledBy.description':
    'Ids of external elements that label the sidebar landmark. Takes precedence over ariaLabel.',
  'sidebar.api.active.description':
    'Marks a sanringSidebarMenuButton as the current page and applies active styling.',
  'sidebar.api.disabled.description':
    'Disables a sanringSidebarMenuButton, preventing click activation and adding disabled semantics.',
  'sidebar.accessibility.description':
    'Sidebar renders a named complementary landmark by default. Menu button and action directives preserve native button/link behavior and give non-native hosts button role, focus, and keyboard activation. Use Sheet when the sidebar must appear as a modal mobile overlay.',
  'sidebar.keyboard.description':
    'Native controls keep their browser behavior; non-native menu controls support button keyboard behavior.',
  'sidebar.keyboard.tab': 'Moves through focusable controls and links in document order.',
  'sidebar.keyboard.enterSpace':
    'Activates buttons. Anchors activate with Enter according to native browser behavior.',
  'sidebar.stateModel.description':
    "open describes whether the sidebar is expanded. collapsible controls what closed means: 'offcanvas' removes the layout width, while 'icon' keeps an icon rail. For external header buttons, control [(open)] directly; sanringSidebarTrigger is intended for descendants of sanring-sidebar.",
} as const;
