export const sidebarTranslations = {
  'sidebar.description':
    'A composable app-shell navigation area with optional offcanvas and icon-rail collapse modes.',
  'sidebar.examples.basic.description':
    'A sidebar participates in page layout and can collapse without becoming a modal overlay.',
  'sidebar.usage.description':
    'Use sidebar primitives to compose application navigation, account switchers, grouped links, and footer actions.',
  'sidebar.installation.description':
    'Install the sidebar primitives and import the convenience array or individual building blocks.',
  'sidebar.composition.description':
    'The sidebar keeps structure separate from interactive links. Use menu button as a directive on anchors or buttons.',
  'sidebar.demo.platform': 'Platform',
  'sidebar.demo.dashboard': 'Dashboard',
  'sidebar.demo.customers': 'Customers',
  'sidebar.demo.notifications': 'Notifications',
  'sidebar.demo.settings': 'Settings',
  'sidebar.demo.overview': 'Overview',
  'sidebar.demo.reports': 'Reports',
  'sidebar.demo.accounts': 'Accounts',
  'sidebar.demo.segments': 'Segments',
  'sidebar.demo.inbox': 'Inbox',
  'sidebar.demo.rules': 'Rules',
  'sidebar.demo.toggle': 'Toggle sidebar',
  'sidebar.demo.iconMode': 'Icon rail',
  'sidebar.demo.offcanvasMode': 'Offcanvas',
  'sidebar.api.description':
    'Sidebar inputs control identity, collapse strategy, state, and link presentation.',
  'sidebar.api.id.description':
    'Sets the id used by trigger aria-controls. A stable id is generated by default.',
  'sidebar.api.open.description':
    'Controls the expanded state. Supports two-way binding with [(open)]. Ignored when collapsible is none.',
  'sidebar.api.collapsible.description':
    'Defines the closed behavior: none stays open, offcanvas collapses to zero width, and icon keeps a compact rail.',
  'sidebar.api.class.description': 'Merges extra classes into the sidebar or slot host element.',
  'sidebar.api.active.description':
    'Marks a sanringSidebarMenuButton as the current page and applies active styling.',
  'sidebar.api.disabled.description':
    'Disables a sanringSidebarMenuButton, preventing click activation and adding disabled semantics.',
  'sidebar.accessibility.description':
    'Sidebar renders persistent layout content. It does not trap focus, hide background content, or behave like a dialog. Use Sheet when the sidebar must appear as a modal mobile overlay.',
  'sidebar.keyboard.description':
    'Keyboard behavior follows the native element used with each directive.',
  'sidebar.keyboard.tab': 'Moves through focusable controls and links in document order.',
  'sidebar.keyboard.enterSpace':
    'Activates buttons. Anchors activate with Enter according to native browser behavior.',
  'sidebar.stateModel.description':
    "open describes whether the sidebar is expanded. collapsible controls what closed means: 'offcanvas' removes the layout width, while 'icon' keeps an icon rail. For external header buttons, control [(open)] directly; sanringSidebarTrigger is intended for descendants of sanring-sidebar.",
} as const;
