export const sliderTranslations = {
  'slider.description':
    'A range control for selecting a numeric value with pointer, touch, keyboard, and Angular forms support.',
  'slider.examples.basic.description':
    'Use sanring-slider when users need to adjust a bounded numeric value directly.',
  'slider.usage.description':
    'Import SliderComponent and bind valueChange or Angular forms to receive numeric updates.',
  'slider.installation.description':
    'Install the slider component and provide an accessible label with ariaLabel or ariaLabelledBy.',
  'slider.demo.step': 'Step',
  'slider.demo.form': 'Form field',
  'slider.demo.disabled': 'Disabled',
  'slider.demo.volume': 'Volume',
  'slider.demo.rating': 'Rating',
  'slider.demo.brightness': 'Brightness',
  'slider.demo.locked': 'Locked value',
  'slider.demo.field': 'With Field',
  'slider.demo.minVolume': 'Minimum volume',
  'slider.demo.fieldError': 'Volume must be at least 80.',
  'slider.examples.field.description':
    'Wrap sanring-slider in sanring-field and bind a reactive form control — the error message shows automatically once the control is invalid and touched.',
  'slider.api.description': 'Inputs and outputs supported by sanring-slider.',
  'slider.api.class.description': 'Additional classes merged with the slider root styles.',
  'slider.api.id.description': 'The slider id. Generated by default.',
  'slider.api.min.description': 'Minimum allowed value.',
  'slider.api.max.description': 'Maximum allowed value.',
  'slider.api.step.description': 'Increment used by pointer rounding and keyboard changes.',
  'slider.api.value.description':
    'Current numeric value. Values are clamped to min/max and snapped to step.',
  'slider.api.disabled.description': 'Disables pointer and keyboard interaction.',
  'slider.api.valueChange.description': 'Emits the next numeric value after user interaction.',
  'slider.api.ariaLabel.description': 'Accessible label when no visible label is associated.',
  'slider.api.ariaLabelledBy.description': 'Id of the visible label element that names the slider.',
  'slider.api.ariaDescribedBy.description': 'Id of helper text that describes the slider.',
  'slider.api.ariaValueText.description':
    'Human-readable value text when the number alone is not enough.',
} as const;
